name: Push Docker Image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          docker build --file Dockerfile --tag $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ github.sha }}
          docker push $DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ github.sha }}
        env:
          DOCKERHUB_USERNAME: ${{ secrets.adenekanoladapo63@gmail.com }}
          DOCKERHUB_PASSWORD: ${{ secrets.Banana234! }}
